kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-metrics-exporter
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - oauths
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch  
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles/finalizers
  verbs:
    - create
    - patch
    - update
- apiGroups:
    - user.openshift.io
  resources:
    - groups
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - user.openshift.io
  resources:
    - groups/finalizers
  verbs:
    - create
    - patch
    - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - update
